# pytorch_lightning==1.7.6
seed_everything: 42
trainer:
  logger: true
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
model:
  enc_in: 2
  factor: 5
  d_model: 512
  n_heads: 8
  e_layers: 3
  d_ff: 512
  dropout: 0.05
  attn: prob
  activation: gelu
  output_attention: false
  distil: true
  learning_rate: 0.001
  encoder_ckpt: ./lightning_logs/informer_fix_pc_500seq_120epochs/checkpoints/epoch=120-step=2057.ckpt
  freeze_encoder: false
data:
  data_dir: ./data/processed/output
  label_filepath: ./data/processed/EML1_pageLevel_500+_matchEDMinstances.csv
  label_col: Rote_X
  load_setup_path: null
  test_dir: null
  train_dataset: null
  test_dataset: null
  train_fold: null
  val_fold: null
  sequence_length: 500
  num_workers: 4
  batch_size: 64
  pin_memory: true
  drop_last: true
  scale: true
ckpt_path: null
