seed_everything: 21
trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 2
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  flush_logs_every_n_steps: null
  log_every_n_steps: 30
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 0
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: true
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: true
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
model:
  max_encoder_sequence_length: 250
  encoder_hidden_dim: 128
  encoder_weights_path: ''
  classifier_hidden_layers:
  - 256
  - 512
  pos_weight:
  - 0.35
  n_output: 1
  learning_rate: 0.001
  dropout: 0.5
  freeze_encoder: false
data:
  data_dir: ./data/processed/output
  label_filepath: ./data/EML/EML1_pageLevel_500+_matchEDMinstances.csv
  label_col: Rote_X
  test_dir: null
  train_dataset: null
  test_dataset: null
  train_fold: null
  val_fold: null
  sequence_length: 3000
  num_workers: 4
  batch_size: 16
  pin_memory: true
  drop_last: true
num_folds: 2
export_path: ./
